name: build ci

on:
  push:
    branches: [ "test-ci" ]
  pull_request:
    branches: [ "test-ci" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Updating packages database
      run: sudo apt-get -qq update

    - name: Install CLI Dependencies
      run: sudo apt-get install -y curl

    - name: prepare glauth
      run: |
        curl -L -o glauth https://github.com/glauth/glauth/releases/download/v2.2.0-RC1/glauth-linux-amd64
        chmod +x glauth

    - name: run glauth
      run: |
        curl -L -o sample.cfg https://raw.githubusercontent.com/glauth/glauth/master/v2/sample-simple.cfg
        ./glauth -c sample.cfg &
        sleep 5

    - name: build
      run: make build

    - name: test-run
      run: |
        make test-run
        sleep 5

    - name: test
      run: |
        make test
        sleep 5
