name: build ci

on:
  push:
    branches: [ "test-ci" ]
  pull_request:
    branches: [ "test-ci" ]

jobs:
  test-bind:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: prepare glauth
      run: |
        curl -L -o glauth https://github.com/glauth/glauth/releases/download/v2.2.0-RC1/glauth-linux-amd64
        chmod +x glauth

    - name: run glauth
      run: |
        curl -L -o sample.cfg https://raw.githubusercontent.com/glauth/glauth/master/v2/sample-simple.cfg
        ./glauth -c sample.cfg &
        sleep 5

    - name: build
      run: make build

    - name: test-bind_mode
      run: make test-bind_mode

  test-search:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: prepare glauth
        run: |
          curl -L -o glauth https://github.com/glauth/glauth/releases/download/v2.2.0-RC1/glauth-linux-amd64
          chmod +x glauth

      - name: run glauth
        run: |
          curl -L -o sample.cfg https://raw.githubusercontent.com/glauth/glauth/master/v2/sample-simple.cfg
          ./glauth -c sample.cfg &
          sleep 5

      - name: build
        run: make build

      - name: test-search-mode
        run: make test-search-mode
